### ISSUE TITLE
Unable to open Youtube Downloader, for Apple cannot check for the absence of malicious software

### ISSUE THREAD

**Issue by sylvainsab** [DenBeke/YouTube-Downloader-for-macOS#10]
This is what pops up when I try to open the app from the Launchpad menu. (I translated from French)

A second line of text says : This software has to be updated. Turn to the developer for more information.

Meanwhile I just installed the app on an up-to-date Mac OS 11.4 Big Sur.
Is Youtube Downloader incompatible with M1 yet ?

**Comment by DenBeke** [comment]
The application is indeed no signed with valid developer certificate. This because I don't pay the 100 euros per year to Apple for a developer account. So every first time the app is opened it will give this notice.

You can prevent it by opening it via right click:
> If you cannot open the app because of 'unidentified developer': Right click on the app and then select 'Open'. A dialog will appear. Click again on 'Open'. From now on you can always open the app without needing to right click on it. More info: [Apple Support](https://support.apple.com/kb/PH25088)

I hope this answers your question. Otherwise feel free to re-open this issue.
