### ISSUE TITLE
Received error that app needs to be updated

### ISSUE THREAD

**Issue by ICU184** [DenBeke/YouTube-Downloader-for-macOS#11]
Received an error that the app needs to be updated.  The program does not show that it is running or will not run on my Macbook Air (M1) running version 11.4.

**Comment by DenBeke** [comment]
The application is not signed with valid developer certificate. This because I don't pay the 100 euros per year to Apple for a developer account. So every first time the app is opened it will give this notice.

You can prevent it by opening it via right click:
> If you cannot open the app because of 'unidentified developer': Right click on the app and then select 'Open'. A dialog will appear. Click again on 'Open'. From now on you can always open the app without needing to right click on it. More info: [Apple Support](https://support.apple.com/kb/PH25088)

I hope this answers your question. Otherwise feel free to re-open this issue.

**Comment by shinra-electric** [comment]
I think the message saying that the app needs to be updated is related to the python version. 

According to [here](https://developer.apple.com/forums/thread/691799) this error is shown if the app uses python 2.7. Apple are displaying the warning because macOS 13 will only have python 3 pre-installed.

**Comment by DenBeke** [comment]
> Not that I see any python scripts in the code though.....

The app uses [youtube-dl](https://youtube-dl.org) in the background, which is programmed in Python. So I suppose you're right.  
Just impossible for me to reproduce the error here.

**Comment by shinra-electric** [comment]
Just an FYI, YouTube-dl has some new developers taking over. 

https://github.com/ytdl-org/youtube-dl/issues/30568

The old version of youtube-dl will continue to be developed, but there is a new branch called yt-dlp that I believe uses more modern Python and has more features.   

https://github.com/yt-dlp/yt-dlp

**Comment by DenBeke** [comment]
Thank you for the heads-up. I will look into migrating to `yt-dlp`, otherwise the app will break in macOS 12.3 since Python 2 support will finally be dropped in macOS.

**Comment by DenBeke** [comment]
I have updated the app to work with `yt-dlp`. This should fix the problem.
https://github.com/DenBeke/YouTube-Downloader-for-macOS/releases/tag/v0.9
