### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by dhru7en** [DenBeke/YouTube-Downloader-for-macOS#15]
For me it works in macOS Monterey. Just had a quick question: when will the stable version be released? 
Also a suggestion would be adding a feature to allow multiple video downloads.

Thanks once again!

**Comment by DenBeke** [comment]
I don't have time to react on every change right away, that's why I keep it as a beta. Also the error handling could be a bit better.
So yeah, the answer is maybe "never" ;)

Regarding multiple video downloads: that would require me to completely overhaul the core of the application, so that won't be something I see happening in the near future.
